trigger:
  - none
  # - master

pool:
  name: Default

steps:
  - bash: |
      dotnet restore 
      dotnet test Identity.UnitTests --logger 'trx;LogFileName=TestResult.trx' --collect 'XPlat Code Coverage'
    displayName: "Build and Test"

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testResultsFormat: "VSTest"
      testResultsFiles: "$(Build.SourcesDirectory)/Identity.UnitTests/TestResults/TestResult.trx"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish Code Coverage Results"
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(Build.SourcesDirectory)/Identity.UnitTests/TestResults/*/coverage.cobertura.xml"

  - task: DotNetCoreCLI@2
    displayName: "Publish Api Code"
    inputs:
      command: publish
      workingDirectory: Identity
      arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)"
      publishWebProjects: False
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"

  - task: AzureRmWebAppDeployment@4
    displayName: "Deploy Api"
    inputs:
      ConnectionType: "AzureRM"
      azureSubscription: "service-connection-zuhid"
      appType: "webAppLinux"
      WebAppName: "zuhid-app-identity"
      packageForLinux: "$(Build.ArtifactStagingDirectory)/a.zip"

  # - bash: |
  #     dotnet new tool-manifest
  #     dotnet tool install dotnet-ef --add-source "https://api.nuget.org/v3/index.json"
  #   displayName: Install Entity Framework Tool

  # - bash: dotnet ef database update --project Api --connection '$(IdentityDbContext)'
  #   displayName: Deploy Database
